#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include "codegen.h"

static void c_string(FILE *out, const char *s) {
    fputc('"', out);
    for (const unsigned char *p = (const unsigned char *)s; *p; p++) {
        switch (*p) {
            case '\\': fputs("\\\\", out); break;
            case '"':  fputs("\\\"", out); break;
            case '\n': fputs("\\n", out); break;
            case '\r': fputs("\\r", out); break;
            case '\t': fputs("\\t", out); break;
            default:
                if (isprint(*p)) fputc(*p, out);
                else fprintf(out, "\\%03o", *p);
        }
    }
    fputc('"', out);
}

static void emit_simple_op(FILE *out, const char *name, const char *function) {
    fprintf(out, "        if (strcmp(op, ");
    c_string(out, name);
    fprintf(out, ") == 0) { %s(&vm); ip++; continue; }\n", function);
}

void codegen_program(const Program *p, FILE *out) {
    fprintf(out, "/* Generated by slasm2c. */\n#include \"slasm_rt.h\"\n\n");
    fprintf(out, "int main(void) {\n    VM vm;\n    vm_init(&vm);\n\n");
    fprintf(out, "    static const char *const program[] = {\n");
    if (p->icount == 0) fprintf(out, "        NULL,\n");
    for (int i = 0; i < p->icount; i++) {
        fprintf(out, "        ");
        c_string(out, p->instructions[i]);
        fprintf(out, ",\n");
    }
    fprintf(out, "    };\n    static const Label labels[] = {\n");
    if (p->lcount == 0) fprintf(out, "        { NULL, 0 },\n");
    for (int i = 0; i < p->lcount; i++) {
        fprintf(out, "        { ");
        c_string(out, p->labels[i].name);
        fprintf(out, ", %d },\n", p->labels[i].ip);
    }
    fprintf(out, "    };\n\n");
    fprintf(out,
        "    long ip = 1;\n"
        "    while (ip <= %d) {\n"
        "        const char *op = program[ip - 1];\n"
        "        if (strcmp(op, \"push\") == 0) {\n"
        "            if (ip == %d) die(\"Missing value after push\");\n"
        "            op_push(&vm, program[ip]);\n"
        "            ip += 2;\n"
        "            continue;\n"
        "        }\n",
        p->icount, p->icount);

    emit_simple_op(out, "+", "op_add");
    emit_simple_op(out, "-", "op_sub");
    emit_simple_op(out, "*", "op_mul");
    emit_simple_op(out, "/", "op_div");
    emit_simple_op(out, "%", "op_mod");
    emit_simple_op(out, "=", "op_eq");
    emit_simple_op(out, "<", "op_lt");
    emit_simple_op(out, ">", "op_gt");
    emit_simple_op(out, "!", "op_not");
    emit_simple_op(out, "W", "op_W");
    emit_simple_op(out, "R", "op_R");
    emit_simple_op(out, "swap", "op_swap");
    emit_simple_op(out, "clearstack", "op_clearstack");
    emit_simple_op(out, "_", "op_under");
    emit_simple_op(out, "getstack", "op_getstack");
    emit_simple_op(out, "cstack", "op_cstack");
    emit_simple_op(out, "clog", "op_clog");
    emit_simple_op(out, "throw", "op_throw");
    emit_simple_op(out, "~", "op_concat");
    emit_simple_op(out, "JOIN", "op_join");
    emit_simple_op(out, "rep", "op_rep");
    emit_simple_op(out, "char", "op_char");
    emit_simple_op(out, "L", "op_L");
    emit_simple_op(out, "S", "op_S");
    emit_simple_op(out, "q", "op_q");
    emit_simple_op(out, "?*", "op_rand");
    emit_simple_op(out, "wait", "op_wait");
    fprintf(out, "        if (strcmp(op, \"gln\") == 0) { op_gln(&vm, labels, %d); ip++; continue; }\n", p->lcount);
    fprintf(out,
        "        if (strcmp(op, \"begin\") == 0 || strcmp(op, \"none\") == 0) { ip++; continue; }\n"
        "        if (strcmp(op, \"jump\") == 0) {\n"
        "            long target = pop_target(&vm);\n"
        "            if (target < 1 || target > %d) die(\"jump: target out of range\");\n"
        "            ip = target;\n"
        "            continue;\n"
        "        }\n"
        "        if (strcmp(op, \"?\") == 0) {\n"
        "            long target = pop_target(&vm);\n"
        "            Value condition = pop(&vm);\n"
        "            if (strcmp(to_str(condition), \"true\") == 0) {\n"
        "                if (target < 1 || target > %d) die(\"?: target out of range\");\n"
        "                ip = target;\n"
        "            } else { ip++; }\n"
        "            continue;\n"
        "        }\n"
        "        fprintf(stderr, \"Undefined operator '%%s'\\n\", op);\n"
        "        return 1;\n"
        "    }\n"
        "    return 0;\n"
        "}\n",
        p->icount + 1, p->icount + 1);
}
