/* Generated by slasm2c. */
#include "slasm_rt.h"

int main(void) {
    VM vm;
    vm_init(&vm);

    static const char *const program[] = {
        "push",
        "1",
        "push",
        "hello",
        "push",
        "0",
        "S",
        "~",
        "W",
        "push",
        "2",
        "push",
        "1",
        "R",
        "push",
        "world",
        "~",
        "W",
        "push",
        "1",
        "push",
        "2",
        "R",
        "push",
        "!",
        "~",
        "W",
        "push",
        "1",
        "R",
        "clog",
    };
    static const Label labels[] = {
        { NULL, 0 },
    };

    long ip = 1;
    while (ip <= 31) {
        const char *op = program[ip - 1];
        if (strcmp(op, "push") == 0) {
            if (ip == 31) die("Missing value after push");
            op_push(&vm, program[ip]);
            ip += 2;
            continue;
        }
        if (strcmp(op, "+") == 0) { op_add(&vm); ip++; continue; }
        if (strcmp(op, "-") == 0) { op_sub(&vm); ip++; continue; }
        if (strcmp(op, "*") == 0) { op_mul(&vm); ip++; continue; }
        if (strcmp(op, "/") == 0) { op_div(&vm); ip++; continue; }
        if (strcmp(op, "%") == 0) { op_mod(&vm); ip++; continue; }
        if (strcmp(op, "=") == 0) { op_eq(&vm); ip++; continue; }
        if (strcmp(op, "<") == 0) { op_lt(&vm); ip++; continue; }
        if (strcmp(op, ">") == 0) { op_gt(&vm); ip++; continue; }
        if (strcmp(op, "!") == 0) { op_not(&vm); ip++; continue; }
        if (strcmp(op, "W") == 0) { op_W(&vm); ip++; continue; }
        if (strcmp(op, "R") == 0) { op_R(&vm); ip++; continue; }
        if (strcmp(op, "swap") == 0) { op_swap(&vm); ip++; continue; }
        if (strcmp(op, "clearstack") == 0) { op_clearstack(&vm); ip++; continue; }
        if (strcmp(op, "_") == 0) { op_under(&vm); ip++; continue; }
        if (strcmp(op, "getstack") == 0) { op_getstack(&vm); ip++; continue; }
        if (strcmp(op, "cstack") == 0) { op_cstack(&vm); ip++; continue; }
        if (strcmp(op, "clog") == 0) { op_clog(&vm); ip++; continue; }
        if (strcmp(op, "throw") == 0) { op_throw(&vm); ip++; continue; }
        if (strcmp(op, "~") == 0) { op_concat(&vm); ip++; continue; }
        if (strcmp(op, "JOIN") == 0) { op_join(&vm); ip++; continue; }
        if (strcmp(op, "rep") == 0) { op_rep(&vm); ip++; continue; }
        if (strcmp(op, "char") == 0) { op_char(&vm); ip++; continue; }
        if (strcmp(op, "L") == 0) { op_L(&vm); ip++; continue; }
        if (strcmp(op, "S") == 0) { op_S(&vm); ip++; continue; }
        if (strcmp(op, "q") == 0) { op_q(&vm); ip++; continue; }
        if (strcmp(op, "?*") == 0) { op_rand(&vm); ip++; continue; }
        if (strcmp(op, "wait") == 0) { op_wait(&vm); ip++; continue; }
        if (strcmp(op, "gln") == 0) { op_gln(&vm, labels, 0); ip++; continue; }
        if (strcmp(op, "begin") == 0 || strcmp(op, "none") == 0) { ip++; continue; }
        if (strcmp(op, "jump") == 0) {
            long target = pop_target(&vm);
            if (target < 1 || target > 32) die("jump: target out of range");
            ip = target;
            continue;
        }
        if (strcmp(op, "?") == 0) {
            long target = pop_target(&vm);
            Value condition = pop(&vm);
            if (strcmp(to_str(condition), "true") == 0) {
                if (target < 1 || target > 32) die("?: target out of range");
                ip = target;
            } else { ip++; }
            continue;
        }
        fprintf(stderr, "Undefined operator '%s'\n", op);
        return 1;
    }
    return 0;
}
